version: "3.9"
services: 
  bot:
    build:
      context: .
      dockerfile: packages/bot/Dockerfile
    env_file: .env
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    env_file: .env
    environment:
      REDIS_URL: "redis://redis:6379"
      API_PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes: 
      - redis:/data

volumes:
  redis: