version: "3.9"
services: 
  bot:
    build:
      context: .
      dockerfile: packages/bot/Dockerfile
    env_file: packages/bot/.env
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis
  redis:
    image: redis:alpine