version: "3.9"
services: 
  bot:
    build:
      context: .
      dockerfile: packages/bot/Dockerfile
    env_file: .env
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    env_file: .env
    environment:
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis:alpine