name: Build and push Docker image
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push bot image
        id: docker_bot_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ramisab/collect-stickers-bot:latest
          file: packages/bot/Dockerfile
      
      - name: Image digest
        run: echo ${{ steps.docker_bot_build.outputs.digest }}
        
      - name: Build api image
        id: docker_api_build
        uses: docker/build-push-action@v2
        with:
          tags: ramisab/collect-stickers-bot/api:latest
          file: packages/api/Dockerfile
        
        